# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o esmt.o gigadevice.o macronix.o micron.o paragon.o
spinand-objs += toshiba.o winbond.o xtx.o dosilicon.o etron.o fmsh.o
spinand-objs += foresee.o gsto.o alliancememory.o ato.o skyhigh.o
spinand-objs += biwin.o hiksemi.o hyf.o jsc.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
